# The root of the RFD repository
rfd-root-directory: /home/redazzo/project/rfdcopy/rfd/test

# The relative location (to the rfd root) of the rfd's. Is usually blank.
rfd-relative-directory: test

# Installation directory of the rfd commandline tool. This is where the templates will be sourced from
install-directory: /home/redazzo/project/rfdcopy/rfd

# The ssh secret key file
private-key-file-name: id_rsa #id_ed25519

rfd-initial-author: "Bob the Taylor"
organisation: "Test Organisation"
instigation-date: "October 2021"

rfd-states:
  - state:
      id: 1
      name: draft
      description: "The first draft, can be used to capture the beginnings of a thought, or even just a single sentence so that it's not forgotten. A document in the draft state contains at least a description of the topic that the RFD will cover, providing an indication of the scope of the eventual RFD."
  - state:
      id: 2
      name: discussion
      description: "Documents under active discussion should be in the discussion state, with the discussion taking place in an active Pull Request."
  - state:
      id: 3
      name: accepted
      description: "Once (or if) discussion has converged and the Pull Request is ready to be merged, it should be updated to the accepted state before being merged into master. Note that just because something is in the accepted state does not mean that it cannot be updated and corrected."
  - state:
      id: 4
      name: committed
      description: "Once an idea is being acted on (e.g. being built, coded, or moved into an operational state), it is moved to the committed state. Comments on RFDs in the committed state should generally be raised as issues -- but if the comment represents a call for a significant divergence from or extension to committed functionality, a new RFD may be called for; as in all things, use your best judgment."
  - state:
      id: 5
      name: abandoned
      description: "If an idea is found to be non-viable (that is, deliberately never implemented after having been accepted) it can be moved into the abandoned state."