rfd-root-directory: /home/redazzo/project/RFD/script/test
rfd-relative-directory: script/test
install-directory: /home/redazzo/project/RFD
private-key-file-name: id_rsa #id_ed25519.pub

rfd-states:
  - ideation
  - discussion
  - accepted
  - implementing
  - committed
  - legacy
  - abandoned

rfd-state-description:
  ideation: "Ideation description"
  discussion: "Discussion description"
  accepted: "Accepted description"
  implementing: "Implementing description"
  committed: "Committed description"
  legacy: "Legacy description"
  abandoned: "Abandoned description"
