# The root of the RFD repository
root-directory: /home/redazzo/project/rfdcopy/rfd/test

# Templates directory of the rfd commandline tool. This is where the templates will be sourced from
templates-directory: /home/redazzo/project/rfdcopy/rfd

# The ssh secret key file
private-key-file-name: id_rsa #id_ed25519

initial-author: "Bob the Taylor"
organisation: "Test Organisation"
instigation-date: "October 2021"