rfd-root-directory: /home/redazzo/project/rfdcopy/rfd/script/test
rfd-relative-directory: script/test
install-directory: /home/redazzo/project/rfdcopy/rfd
private-key-file-name: id_rsa #id_ed25519


#rfd-root-directory: C:\Users\gerha\project\RFD\script\test
#rfd-relative-directory: script\test
#install-directory: C:\Users\gerha\project\RFD
#private-key-file-name: id_rsa #id_ed25519

organisation: "Test Organisation"
instigation-date: "October 2021"

rfd-states:
  - state:
      id: 1
      name: ideation
      description: "Ideation description"
  - state:
      id: 2
      name: discussion
      description: "Discussion description"
  - state:
      id: 3
      name: accepted
      description: "Accepted description"
  - state:
      id: 4
      name: implementing
      description: "Description description"
  - state:
      id: 5
      name: committed
      description: "Committed description"
  - state:
      id: 6
      name: legacy
      description: "Legacy description"
  - state:
      id: 7
      name: abandoned
      description: "Abandoned description"